---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Add Prometheus Helm repository
      command: >
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Update Helm repositories
      command: helm repo update
    
    - name: Create Prometheus namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: prometheus
            labels:
              owner: "team.force"

    - name: Install Prometheus using Helm with custom configurations
      shell: |
        helm install prometheus prometheus-community/prometheus \
          -f /opt/iac/ansible/store/prometheus/values.yml \
          --namespace prometheus
      args:
        executable: /bin/bash
      register: helm_install_output
      failed_when: helm_install_output.rc != 0 and "already exists" not in helm_install_output.stderr