---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Add Kubecost Helm repository
      shell: |
        helm repo add kubecost https://kubecost.github.io/cost-analyzer/
        helm repo update
      args:
        executable: /bin/bash

    - name: Create Kubecost namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: kubecost
            labels:
              owner: "team.force"

    - name: Install Kubecost using Helm
      shell: |
        helm install kubecost \
          --repo https://kubecost.github.io/cost-analyzer/ cost-analyzer \
          --namespace kubecost \
          --set global.prometheus.fqdn=http://prometheus-server.prometheus.svc:80 \
          --set global.prometheus.enabled=false
      args:
        executable: /bin/bash