---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Add Grafana Helm repository
      shell: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update
      args:
        executable: /bin/bash

    - name: Create Grafana namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: grafana
            labels:
              owner: "team.force"

    - name: Install Grafana using Helm
      shell: |
        helm install grafana grafana/grafana --namespace grafana -f /opt/iac/ansible/store/grafana/*
      args:
        executable: /bin/bash