---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Add Grafana Helm repository
      shell: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update
      args:
        executable: /bin/bash

    - name: Create custom grafana-values.yaml for Grafana resources
      copy:
        dest: /tmp/grafana-values.yaml
        content: |
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

    - name: Install Grafana using Helm
      shell: |
        helm install grafana grafana/grafana --namespace grafana --create-namespace -f /tmp/grafana-values.yaml
      args:
        executable: /bin/bash

    - name: Set up port-forwarding for Grafana
      shell: |
        sudo nohup kubectl port-forward --address 0.0.0.0 --namespace grafana service/grafana 3000:80 > /tmp/port-forward-grafana.log 2>&1 &
      args:
        executable: /bin/bash