---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Add Prometheus Helm repository
      command: >
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Update Helm repositories
      command: helm repo update
    
    - name: Create Prometheus namespace
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: prometheus
            labels:
              owner: "team.force"

    - name: Create Discord webhook secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: discord-webhook
            namespace: prometheus
          type: Opaque
          stringData:
            webhook-url: "{{ discord_webhook_url }}"

    - name: Install Prometheus using Helm with custom configurations
      shell: |
        helm install prometheus prometheus-community/prometheus \
          -f /opt/iac/ansible/store/prometheus/* \
          --namespace prometheus
      args:
        executable: /bin/bash
      register: helm_install_output
      failed_when: helm_install_output.rc != 0 and "already exists" not in helm_install_output.stderr