---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Download Minikube binary
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/v1.34.0/minikube-linux-amd64"
        dest: "/usr/local/bin/minikube"
        mode: '0755'

    - name: Verify Minikube installation
      command: "minikube version"
      register: minikube_version
      changed_when: false

    - name: Get the latest stable Kubernetes version
      command: "curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt"
      register: kubectl_version

    - name: Install kubectl
      get_url:
        url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version.stdout }}/bin/linux/amd64/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: '0755'

    - name: Verify kubectl installation
      command: "kubectl version --client"
      register: kubectl_version_output
      changed_when: false

    - name: Start Minikube with 2 nodes and RBAC enabled
      command: "sudo minikube start --nodes 2 --driver=docker --memory=8192 --cpus=4 --force"

    - name: Wait for Minikube to be ready
      command: "minikube status"
      register: minikube_status
      until: "'host' in minikube_status.stdout"
      retries: 5
      delay: 10

    - name: Show Minikube status
      debug:
        msg: "{{ minikube_status.stdout }}"

    - name: Create systemd service file for Minikube
      copy:
        dest: /etc/systemd/system/minikube.service
        content: |
          [Unit]
          Description=Minikube Kubernetes Cluster
          After=network.target docker.service
          
          [Service]
          Type=oneshot
          RemainAfterExit=yes
          User=root
          ExecStart=/usr/local/bin/minikube start --nodes 2 --driver=docker --memory=8192 --cpus=4 --force
          ExecStop=/usr/local/bin/minikube stop
          
          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable Minikube service
      systemd:
        name: minikube
        enabled: yes
        state: started

    - name: Verify Minikube service status
      command: systemctl status minikube
      register: service_status
      changed_when: false

    - name: Display service status
      debug:
        msg: "{{ service_status.stdout_lines }}"

    - name: Get all nodes
      kubernetes.core.k8s_info:
        kind: Node
        api_version: v1
      register: nodes_list

    - name: Label first node as master
      kubernetes.core.k8s:
        state: present
        kind: Node
        name: "{{ nodes_list.resources[0].metadata.name }}"
        definition:
          metadata:
            labels:
              node-role: master
      when: nodes_list.resources | length > 0

    - name: Label second node as slave
      kubernetes.core.k8s:
        state: present
        kind: Node
        name: "{{ nodes_list.resources[1].metadata.name }}"
        definition:
          metadata:
            labels:
              node-role: slave
      when: nodes_list.resources | length > 1
