---
- hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Include Docker setup playbook
    import_playbook: install_docker.yml

  - name: Include Minikube setup playbook
    import_playbook: install_minikube.yml

  - name: Include Helm setup playbook
    import_playbook: install_helm.yml

  - name: Include Cert Manager setup playbook
    import_playbook: deploy_cert_manager.yml

  - name: Include WebGoat setup playbook
    import_playbook: deploy_webgoat.yml