name: Run Ansible Playbook

on:
  workflow_run:
    workflows:
      - Production Release Workflow
    types:
      - completed

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run Ansible Playbook
      uses: dawidd6/action-ansible-playbook@v2.8.0
      with:
        playbook: deploy_webgoat.yml

        directory: ./ansible

        # Inventory file content
        inventory: |
          [webgoat_host]
          ${{ vars.DEPLOYMENT_SERVER }} ansible_ssh_user=${{ vars.ANSIBLE_SSH_USER }} ansible_ssh_pass=${{ secrets.ANSIBLE_SSH_PASSWORD }}