name: Run DAST

on:
  push:
    branches:
      - 'release/**'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Dynamic Application Security Testing (DAST)
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-full-scan@v0.11.0
      with:
        target: ${{ vars.WEB_APP_DNS }}
